from __future__ import annotations

from datetime import timedelta
from typing import Final

DOMAIN: Final = "swegon_casa"

CONF_DEVICE_ID: Final = "device_id"
CONF_DEVICE_NAME: Final = "device_name"
CONF_SERIAL_NUMBER: Final = "serial_number"

LOGIN_URL: Final = "https://api.ouman.io/login"
WEBSOCKET_URL: Final = (
    "wss://oulite.ouman.io/socket.io/"
    "?EIO=4&transport=websocket"
)
ORIGIN: Final = "https://swegoncasa.io"

RECONNECT_DELAY: Final = 5
KEEPALIVE_INTERVAL: Final = 25

PLATFORMS: Final = [
    "sensor",
    "binary_sensor",
    "select",
    "number",
]

PROPERTY_VALUE: Final = "85"
DEVICE_ADDRESS: Final = "255"

OBJECT_SUPPLY_TEMPERATURE: Final = "17"
OBJECT_RETURN_TEMPERATURE: Final = "18"
OBJECT_INTAKE_TEMPERATURE: Final = "19"
OBJECT_CO2: Final = "21"
OBJECT_HUMIDITY: Final = "22"
OBJECT_HUMIDITY_AMOUNT: Final = "23"
OBJECT_AIR_QUALITY: Final = "25"
OBJECT_CURRENT_FAN_SPEED: Final = "27"
OBJECT_VENTILATION_IN: Final = "28"
OBJECT_VENTILATION_OUT: Final = "29"
OBJECT_BOOST_COUNTDOWN: Final = "31"

OBJECT_HUMIDITY_BOOST: Final = "34"
OBJECT_SUMMER_NIGHT_COOLING_BOOST: Final = "36"

OBJECT_FAN_MODE: Final = "111"
OBJECT_TRAVEL_TEMPERATURE_DROP: Final = "121"
OBJECT_CO2_HOME_LIMIT: Final = "122"
OBJECT_CO2_AWAY_LIMIT: Final = "123"
OBJECT_HUMIDITY_BOOST_LIMIT: Final = "124"
OBJECT_HUMIDITY_FULL_BOOST_LIMIT: Final = "125"
OBJECT_FIREPLACE_MODE: Final = "153"
OBJECT_POWER_OFF: Final = "155"
OBJECT_SMART_HUMIDITY_LEVEL: Final = "159"
OBJECT_AUTO_AIR_QUALITY_MODE: Final = "160"
OBJECT_SUMMER_NIGHT_COOLING_BOOST_LEVEL: Final = "161"
OBJECT_SUMMER_NIGHT_COOLING_ACTIVATION_LEVEL: Final = "162"
OBJECT_SUPPLY_SETPOINT: Final = "163"
OBJECT_TEMPERATURE_CONTROL_MODE: Final = "164"
OBJECT_AWAY_TEMPERATURE_DROP: Final = "165"


OBJECT_DEVICE_INFO: Final = "500"

SUBSCRIBED_OBJECTS: Final = [
    OBJECT_SUPPLY_TEMPERATURE,
    OBJECT_RETURN_TEMPERATURE,
    OBJECT_INTAKE_TEMPERATURE,
    OBJECT_CO2,
    OBJECT_HUMIDITY,
    OBJECT_HUMIDITY_AMOUNT,
    OBJECT_AIR_QUALITY,
    OBJECT_CURRENT_FAN_SPEED,
    OBJECT_VENTILATION_IN,
    OBJECT_VENTILATION_OUT,
    OBJECT_BOOST_COUNTDOWN,
    OBJECT_FAN_MODE,
    OBJECT_FIREPLACE_MODE,
    OBJECT_POWER_OFF,
    OBJECT_TRAVEL_TEMPERATURE_DROP,
    OBJECT_CO2_HOME_LIMIT,
    OBJECT_CO2_AWAY_LIMIT,
    OBJECT_HUMIDITY_BOOST_LIMIT,
    OBJECT_HUMIDITY_FULL_BOOST_LIMIT,
    OBJECT_SMART_HUMIDITY_LEVEL,
    OBJECT_AUTO_AIR_QUALITY_MODE,
    OBJECT_SUMMER_NIGHT_COOLING_BOOST_LEVEL,
    OBJECT_SUMMER_NIGHT_COOLING_ACTIVATION_LEVEL,
    OBJECT_SUPPLY_SETPOINT,
    OBJECT_TEMPERATURE_CONTROL_MODE,
    OBJECT_AWAY_TEMPERATURE_DROP,
]